// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zhasyl.Api.Database;

#nullable disable

namespace Zhasyl.Api.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Laboratory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "Order")
                        .IsUnique();

                    b.HasIndex("StationId", "Slug")
                        .IsUnique();

                    b.ToTable("laboratories", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.LaboratoryTranslation", b =>
                {
                    b.Property<Guid>("LaboratoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Specialist")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("LaboratoryId", "Locale");

                    b.ToTable("laboratory_translations", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LaboratoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId", "Order")
                        .IsUnique();

                    b.HasIndex("LaboratoryId", "Slug")
                        .IsUnique();

                    b.ToTable("missions", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.MissionRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyMdx")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId", "Locale")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\"");

                    b.HasIndex("MissionId", "Locale", "Version")
                        .IsUnique();

                    b.ToTable("mission_revisions", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.StationTranslation", b =>
                {
                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Briefing")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("StationId", "Locale");

                    b.ToTable("station_translations", (string)null);
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Laboratory", b =>
                {
                    b.HasOne("Zhasyl.Api.Domain.Content.Station", "Station")
                        .WithMany("Laboratories")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.LaboratoryTranslation", b =>
                {
                    b.HasOne("Zhasyl.Api.Domain.Content.Laboratory", "Laboratory")
                        .WithMany("Translations")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Mission", b =>
                {
                    b.HasOne("Zhasyl.Api.Domain.Content.Laboratory", "Laboratory")
                        .WithMany("Missions")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.MissionRevision", b =>
                {
                    b.HasOne("Zhasyl.Api.Domain.Content.Mission", "Mission")
                        .WithMany("Revisions")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.StationTranslation", b =>
                {
                    b.HasOne("Zhasyl.Api.Domain.Content.Station", "Station")
                        .WithMany("Translations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Laboratory", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Mission", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Zhasyl.Api.Domain.Content.Station", b =>
                {
                    b.Navigation("Laboratories");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
